# Generated by Django 3.0.2 on 2020-04-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200430_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
