# Generated by Django 3.0.2 on 2020-05-01 22:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_issue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='issue',
            new_name='issue_item',
        ),
    ]
