# Generated by Django 3.0.2 on 2020-05-01 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200502_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_item',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='issue_item',
            name='itemu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.inventory'),
        ),
    ]
