# Generated by Django 3.0.2 on 2020-05-02 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_complaints_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints_posted',
            name='Downvote',
        ),
        migrations.AddField(
            model_name='complaints_posted',
            name='Downvote',
            field=models.ManyToManyField(blank=True, related_name='Downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='complaints_posted',
            name='Upvote',
        ),
        migrations.AddField(
            model_name='complaints_posted',
            name='Upvote',
            field=models.ManyToManyField(blank=True, related_name='Upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
