# Generated by Django 3.0.2 on 2020-05-02 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_auto_20200502_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints_posted',
            name='Downvote',
            field=models.ManyToManyField(blank=True, default=0, related_name='Downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaints_posted',
            name='Upvote',
            field=models.ManyToManyField(blank=True, default=0, related_name='Upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
