# Generated by Django 3.1.7 on 2021-08-01 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200502_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints_posted',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
