# Generated by Django 3.1.7 on 2021-08-01 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_complaints_posted_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('product_type', models.CharField(choices=[(1, 'Racket'), (2, 'Grips'), (3, 'Shoes'), (4, 'Shuttle'), (5, 'String'), (6, 'Net')], max_length=100)),
                ('seller_contact', models.CharField(default='123', max_length=100)),
                ('months_old', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[(1, 'Sealed and New'), (2, 'Unboxed but Not used'), (3, 'Used')], max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
