# Generated by Django 3.1.7 on 2021-08-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='roll',
            new_name='pincode',
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Sealed and New', 'Sealed and New'), ('Unboxed but Not used', 'Unboxed but Not used'), ('Used', 'Used')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Racket', 'Racket'), ('Grip', 'Grip'), ('Shoe', 'Shoe'), ('Shuttle', 'Shuttle'), ('String', 'String'), ('Net', 'Net')], max_length=100),
        ),
    ]
